# Generated by Django 2.2.11 on 2020-04-19 08:39

from django.db import migrations, models
import django.db.models.deletion
import staby.media.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
            ],
            options={
                'staby_urls': 'staby.galleries.urls',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', staby.media.fields.FileBrowseField(max_length=255)),
                ('dirname', models.CharField(max_length=255)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='galleries.Gallery')),
            ],
        ),
    ]
